---
title: "Bird beak's elaboration and exploration"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
bibliography: references.bib
output:
  html_document:
    fig_width: 8
    fig_height: 8
---


```{r, echo = FALSE, print = FALSE}
library(dispRity)
library(beer)
library(MCMCglmm)
data(chara_data)
data(chara_tree)
```

## Number of dimensions required to capture at least X% of variance per group


```{r, echo = FALSE}
## Get the groups
beaks <- readRDS("MCMCglmm_covar/Data/2020_06_19_MMB_LANDMARKS_ALL.rds")
order_groups <- lapply(as.list(unique(beaks$Order)), function(X) unique(beaks$TipLabel[beaks$Order %in% X]))
names(order_groups) <- unique(beaks$Order)
family_groups <- lapply(as.list(unique(beaks$Family)), function(X) unique(beaks$TipLabel[beaks$Family %in% X]))
names(family_groups) <- unique(beaks$Family)

## Get the PCA
load("MCMCglmm_covar/full_PCAs.rda")

## Get the results for each group with > 10 species
min_sp <- 10
test_sizefree_order <- select.axes(full_PCAs$sizefree, threshold = 0.95, group = order_groups[-which(unlist(lapply(order_groups, length)) < min_sp)])
test_sizefree_family <- select.axes(full_PCAs$sizefree, threshold = 0.95, group = family_groups[-which(unlist(lapply(family_groups, length)) < min_sp)])
test_sizeform_order <- select.axes(full_PCAs$sizeform, threshold = 0.95, group = order_groups[-which(unlist(lapply(order_groups, length)) < min_sp)])
test_sizeform_family <- select.axes(full_PCAs$sizeform, threshold = 0.95, group = family_groups[-which(unlist(lapply(family_groups, length)) < min_sp)])
```

## Size free PCA loadings per order

```{r, fig.height = 14, fig.width = 12}
plot(test_sizefree_order)
```

## Size free PCA loadings per family

```{r, fig.height = 28, fig.width = 24}
plot(test_sizefree_family)
```

## Size + form PCA loadings per order

```{r, fig.height = 14, fig.width = 12}
plot(test_sizeform_order)
```

## Size + form PCA loadings per family

```{r, fig.height = 28, fig.width = 24}
plot(test_sizeform_family)
```
