---
title: "Linking different metrics to Elaboration and Innovation"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 8
    fig_height: 8
---


## Elaboration and Innovation definitions

For any species with coordinates $\vec{species}$ in a $n$ dimensional space, we can estimate $VCV_{superorder}$ and $VCV_{order}$, respectively two nested variance-covariance matrices representing the any order and super order that contains $\vec{species}$.
We can then calculate the eigen vector and eigenvalues from these matrices as: 

$\textbf{v}_{superorder}$ and $\lambda_{superorder}$ defined as:
$$VCV_{superorder} \textbf{v}_{superorder} = \lambda_{superorder} \textbf{v}_{superorder}$$

and $\textbf{v}_{order}$ and $\lambda_{order}$ defined as:
$$VCV_{order} \textbf{v}_{order} = \lambda_{order} \textbf{v}_{order}$$

In practice, these are solved using a eigen decomposition in `R` `eigen`.

We can then define the followings:

$$\text{Elaboration}_{\text{species}} = \|\frac{\vec{species} \cdot \textbf{v}_{order}} {\sqrt{\textbf{v}_{order} \cdot \textbf{v}_{order}}}\|$$

$$\text{Innovation}_{\text{species}} = \| \vec{species} - \text{Elaboration}_{\text{species}} \|$$

$$\text{Elaboration}_{\text{clade}} = \| \frac{\textbf{v}_{order} \cdot \textbf{v}_{superorder}} {\sqrt{\textbf{v}_{superorder} \cdot \textbf{v}_{superorder}}}\|$$

$$\text{Innovation}_{\text{clade}} = \| \textbf{v}_{order} - \text{Elaboration}_{\text{clade}} \|$$

## Relative eigenvalues dispersion

$$V_{rel} = \frac{\sum_{i}^{n}(\lambda_{i} - \sum{\frac{\lambda_{i}}{n}})^2}{n(n-1)\sum{\frac{\lambda_{i}}{n}}^2}$$
Which is the dispersion of eigenvalues (squared difference between each eigen value and the average eigen value).


```{r, eval = FALSE}
## Relative eigenvalue dispersion
rel.eigenvalue.dispersion <- function(matrix) {
    ## Getting the eigen values, n and mean eigen value
    lambdas <- eigen(var(matrix))$values
    n <- length(lambdas)
    lambda_mean <- mean(lambdas)
    ## Calculating the relative eigen dispersion
    return(sum((lambdas - lambda_mean)^2)/n*(n-1)*lambda_mean)
}

## Calculating the Elaboration/Innovation for clades and species
data(charadriiformes)

## Creating a dispRity object with a covar component
my_covar <- MCMCglmm.subsets(
                 data       = charadriiformes$data,
                 posteriors = charadriiformes$posteriors,
                 tree       = charadriiformes$tree,
                 group      = MCMCglmm.levels(
                                 charadriiformes$posteriors)[1:4],
                 rename.groups = c("gulls", "plovers", "sandpipers", "phylo"))

## Clade level
clade   <- dispRity.covar.projections(my_covar, type = "groups", base = "phylo", n = 100,  output = c("position", "distance"))
species <- dispRity.covar.projections(my_covar, type = "elements", n = 100,  output = c("position", "distance"))
eigen_dispersion <- dispRity(my_covar, metric = rel.eigenvalue.dispersion)
```





dispersion of eigenvalues of a covariance or correlation matrix




 - [ ] link orthogonality to random skewers
 - [ ] link E/I to relative eigenvector dispersion (Pavlicev et al., 2009, Watanabe, 2022) 
 - [ ] link E/I to conditional evolvability (Hansen & Houle, 2008) 
 - [ ] link E/I to integration (Hansen & Houle, 2008) 

