---
title: "03-elaboration exploration analyses"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

# Elaboration/exploration analyses

## Elaboration/exploration metrics

Measure the different elaboration vs exploration metrics with different vectors:
 
 - [ ] MRCA trajectory: the vector between the root of the tree and the OTU's descendant
 - [ ] MRCA average trajectory: the vector between the centroid of the group's nodes and the root of the tree
 - [ ] Evolutionary living average trajectory: the vector between the root of the tree and the centroid of the living taxa
 - [ ] Evolutionary overall average trajectory: the vector between the root of the tree and the centroid of the tips and nodes
 - [ ] Maximum living trajectory: the vector between the two most distant OTUs
 - [ ] Maximum evolutionary trajectory: the vector between the root and the OTU most distant from the root

## Elaboration/exploration in the present

Apply these metrics on both clades to get two scores for each taxa (elaboration vs. exploration plots).

## Elaboration/exploration through time

Do some time-slicing and run these metrics through time.