---
title: "Bird beak's elaboration and innovation"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
bibliography: references.bib
output:
  html_document:
    fig_width: 8
    fig_height: 8
---

This section contains the code for reproducing the analyses. To get the details, refer to 03-elaboration_innovation_analyses.Rmd.

```{r, eval = TRUE, echo = FALSE, results = 'hide', message = FALSE, warning = FALSE, print = FALSE}
library(dispRity)
source("../Functions/ploting.utilities.R")
source("../Functions/covar.utilities.R")
```

# All birds shapespace analyses

```{r, eval = TRUE, echo = FALSE}
## Load the data
load(file = "../Data/Processed/shapespace_allbirds_lvl_superorder_order.rda")
## Select the data
shapespace <- shapespace_allbirds_lvl_superorder_order[[1]]$space
tree <- shapespace_allbirds_lvl_superorder_order[[1]]$consensus_tree
## Clean garbage
rm(shapespace_allbirds_lvl_superorder_order)

## Load the covar
load(file = "../Data/Processed/shapespace_allbirds_lvl_superorder_order.MCMCglmm")
shapespace_allbirds_lvl_superorder_order <- shapespace_allbirds_lvl_superorder_order[[1]]

## Get the levels
phylo_lvl <- which(MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order) == "animal")
super_lvl <- grep("level1_", MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order))
order_lvl <- grep("level2_", MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order))

## Creating the subsets
superorder_shapespace <- MCMCglmm.subsets(n = 4000, # Just run it on 1k matrices for now
      data          = shapespace,
      posteriors    = shapespace_allbirds_lvl_superorder_order,
      group         = MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order)[c(super_lvl, phylo_lvl)],
      rename.groups = c(levels(shapespace$level1)[-1], "phylogeny")) #[-1] is because the first level is ""

order_shapespace <- MCMCglmm.subsets(n = 4000, # Just run it on 1k matrices for now
      data          = shapespace,
      posteriors    = shapespace_allbirds_lvl_superorder_order,
      group         = MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order)[c(order_lvl, phylo_lvl)],
      rename.groups = c(levels(shapespace$level2)[-1], "phylogeny")) #[-1] is because the first level is ""
## Clean garbage
rm(shapespace_allbirds_lvl_superorder_order)

## Loading the results
load(file = "../Data/Processed/shapespace_allbirds_lvl_superorder_order_results_list_4k.rda")
results <- shapespace_allbirds_lvl_superorder_order_results_list
rm(shapespace_allbirds_lvl_superorder_order_results_list)
```

```{r, eval = TRUE, echo = FALSE}
box_size <- 1.5
pdf(file = "../Manuscript/Figures/Figure3_ellipses.pdf", height = box_size*10, width = box_size*10)

## SETTING THE WINDOW PARAMETERS
## Global window parameters
lay_mat_super <- rbind(
        matrix(c(1,1, rep(73, 3), 0, 2:5), ncol = 10, nrow = 1), # line 7
        matrix(c(1,1, rep(73, 3), 0, 6:9), ncol = 10, nrow = 1), # line 8
        matrix(c(78,78, 10:17), ncol = 10, nrow = 1) # line 8
    )
lay_mat_order <- rbind(
        matrix(c(1,1, rep(57, 3), 60, 2:5), ncol = 10, nrow = 1), 
        matrix(c(1,1, rep(57, 3), 60, 6:9), ncol = 10, nrow = 1), 
        matrix(c(1,1, 10:17), ncol = 10, nrow = 1),
        matrix(c(18:27), ncol = 10, nrow = 1),
        matrix(c(28:37), ncol = 10, nrow = 1), 
        matrix(c(38:47), ncol = 10, nrow = 1),
        matrix(c(48:55, 58:59), ncol = 10, nrow = 1)
    )


heights_vals <- rep(1, 9)
widths_vals <- rep(c(1, 1/3), 5)
layout_matrix <- layout(rbind(lay_mat_super, (lay_mat_order+17)), widths = widths_vals, heights = heights_vals, respect = TRUE)

## PLOTTING THE SUPERORDERS

## Getting the tip order for the ladderised super order tree
tip_order <- c(
    "Paleognathae" = 1,
    "Galloanserae" = 2,
    "Otidimorphae" = 5,
    "Aequornithes" = 6,
    "Mirandornithes" = 3,
    "Columbimorphae" = 4,
    "Telluraves" = 8,
    "Strisores" = 7)

## Plotting the tree and getting the tip orders
tip_colours_super_orders <- plot.short.tree(tree, shapespace, "level1", tip.order = tip_order)
save(tip_colours_super_orders, file = "../Data/Processed/tip_colours_super_orders.rda")

## Plotting the ellipses
for(i in 1:length(tip_order)) {
    ## Plot each pannel
    wrap.plot.ellipses(i, tip_colours_super_orders, superorder_shapespace, results$super_results_between)
}

## Matching colours (fast utility)
match.col <- function(data, col) {
    return(c(col[match(names(size.subsets(data)), names(col))[-length(size.subsets(data))]], "grey"))
}

## Matching the order and the colours to the ladderised tree
tip_order <- c(
    "Tinamiformes"= 1,
    "Galliformes"= 3,
    "Anseriformes"= 2,
    "Otidiformes"= 7,
    "Cuculiformes" = 8,
    "Gruiformes" = 9, 
    "Musophagiformes" = 10,
    "Procellariiformes" = 12,
    "Sphenisciformes" = 11,
    "Ciconiiformes" = 13,
    "Pelecaniformes"= 15,
    "Suliformes" = 14,
    "Podicipediformes" = 4,
    "Columbiformes" = 6,
    "Pterocliformes" = 5,
    "Charadriiformes" = 18,
    "Trogoniformes" = 21,
    "Bucerotiformes" = 22,
    "Coraciiformes" = 23,
    "Piciformes" = 24,
    "Strigiformes" = 20,
    "Accipitriformes" = 19, 
    "Falconiformes" = 25,
    "Psittaciformes" = 26,
    "Passeriformes" = 27,
    "Caprimulgiformes" = 16, 
    "Apodiformes" = 17)

## Plotting the tree and getting the tip orders
tip_colours_orders <- plot.short.tree(tree, shapespace, "level2", tip.order = tip_order)
save(tip_colours_orders, file = "../Data/Processed/tip_colours_orders.rda")

## Plotting the ellipses
for(i in 1:length(tip_order)) {
    ## Plot each pannel
    wrap.plot.ellipses(i, tip_colours_orders, order_shapespace, results$order_results_between)
}


## Plotting the aligned and scale ellipses for the superorders
par(bty = "n")
lims <- c(-1/3, 1/3) # c(-1.25, 1.25)
plot(NULL, xlim = lims, ylim = lims, xaxt = "n", yaxt = "n", xlab = "n", ylab = "n")
abline(v = 0, col = "grey", lwd = 0.5)
abline(h = 0, col = "grey", lwd = 0.5)
covar.plot(superorder_shapespace, ellipses = mean,
           col = match.col(superorder_shapespace, tip_colours_super_orders),
           legend = FALSE, points = FALSE, scale = "phylogeny",
           lines.lwd = c(rep(1, length(tip_colours_super_orders)), 3),
           add = TRUE, n = 100)

## PLOTTING THE ORDERS

par(bty = "n")
lims <- c(-1/3, 1/3) # c(-1.25, 1.25)
plot(NULL, xlim = lims, ylim = lims, xaxt = "n", yaxt = "n", xlab = "n", ylab = "n")
abline(v = 0, col = "grey", lwd = 0.5)
abline(h = 0, col = "grey", lwd = 0.5)
covar.plot(order_shapespace, ellipses = mean,
           col = match.col(order_shapespace, tip_colours_orders),
           legend = FALSE, points = FALSE, scale = "phylogeny",
           lines.lwd = c(rep(0.5, length(tip_colours_orders)), 3),
           add = TRUE, n = 100)

dev.off()

```



# Passeriformes shapespace analyses

```{r, eval = TRUE, echo = FALSE}
## Load the data
load(file = "../Data/Processed/shapespace_passeriformes_two_levels.rda")
## Select the data
shapespace <- shapespace_passeriformes_two_levels[[1]]$space
tree <- shapespace_passeriformes_two_levels[[1]]$consensus_tree
## Clean garbage
rm(shapespace_passeriformes_two_levels)

## Load the covar
load(file = "../Data/Processed/shapespace_passeriformes.MCMCglmm")
shapespace_passeriformes <- shapespace_passeriformes[[1]]

## Get the levels
phylo_lvl <- which(MCMCglmm.levels(shapespace_passeriformes) == "animal")
suborder_lvl <- grep("level1_", MCMCglmm.levels(shapespace_passeriformes))
family_lvl <- grep("level2_", MCMCglmm.levels(shapespace_passeriformes))

## Creating the subsets
suborder_shapespace <- MCMCglmm.subsets(#n = 1000, # Just run it on 1k matrices for now
      data          = shapespace,
      posteriors    = shapespace_passeriformes,
      group         = MCMCglmm.levels(shapespace_passeriformes)[c(suborder_lvl, phylo_lvl)],
      rename.groups = c(levels(shapespace$level1)[-1], "phylogeny")) #[-1] is because the first level is ""

family_shapespace <- MCMCglmm.subsets(#n = 1000, # Just run it on 1k matrices for now
      data          = shapespace,
      posteriors    = shapespace_passeriformes,
      group         = MCMCglmm.levels(shapespace_passeriformes)[c(family_lvl, phylo_lvl)],
      rename.groups = c(levels(shapespace$level2)[-1], "phylogeny")) #[-1] is because the first level is ""
## Clean garbage
rm(shapespace_passeriformes)

## Loading the results
load(file = "../Data/Processed/shapespace_passeriformes_suborder_family_results_list.rda")
results <- shapespace_passeriformes_suborder_family_results_list
rm(shapespace_passeriformes_suborder_family_results_list)
```

## Phylogeny window (detailed)

```{r}
box_size <- 1.5
pdf(file = "../Manuscript/Figures/Figure3_passeriformes.pdf", height = box_size*9, width = box_size*10)

## Global window
x <- 61
lay_mat_sub <- rbind(
        matrix(c(1,1, rep(x, 3), 0, 2:5), ncol = 10, nrow = 1), # line 7
        matrix(c(1,1, rep(x, 3), 0, 6:9), ncol = 10, nrow = 1), # line 8
        matrix(c(x+2,x+2, 10:13, rep(x+3, 4)), ncol = 10, nrow = 1) # line 8
    )
y <- x - 13
lay_mat_family <- rbind(
        matrix(c(1,1, rep(y+1, 3), y+4, 2:5), ncol = 10, nrow = 1), 
        matrix(c(1,1, rep(y+1, 3), y+4, 6:9), ncol = 10, nrow = 1), 
        matrix(c(1,1, 10:17), ncol = 10, nrow = 1),
        matrix(c(18:27), ncol = 10, nrow = 1),
        matrix(c(28:37), ncol = 10, nrow = 1), 
        matrix(c(38:47), ncol = 10, nrow = 1)
    )
heights_vals <- rep(1, 8)
widths_vals <- rep(c(1, 1/3), 5)
layout_matrix <- layout(rbind(lay_mat_sub, (lay_mat_family+13)), widths = widths_vals, heights = heights_vals, respect = TRUE)
# layout.show(layout_matrix)

## PLOTTING THE SUBORDERS

## Getting the tip order for the ladderised super order tree
tip_order <- c(
    "Suboscines" = 1,
    "Meliphagoidea" = 2,
    "Corvides" = 3,
    "Sylviida" = 4,
    "Muscicapida" = 5,
    "Passerida" = 6)

## Plotting the tree and getting the tip orders
tip_colours_passeriformes_suborder <- plot.short.tree(tree, shapespace, "level1", tip.order = tip_order)
save(tip_colours_passeriformes_suborder, file = "../Data/Processed/tip_colours_passeriformes_suborder.rda")

## Plotting the ellipses
for(i in 1:length(tip_order)) {
    ## Plot each pannel
    wrap.plot.ellipses(i, tip_colours_passeriformes_suborder, suborder_shapespace, results$suborder_results_between)
}

## PLOTTING THE FAMILIES

## Matching the order and the colours to the ladderised tree
tip_order <- c(
    "Aegithaloidea"= 12,
    "Bombycilloidea"= 17,
    "Cisticolidae"= 14,
    "Corvoidea"= 7,
    "Emberizoidea"= 23,
    "Eurylaimides"= 1,
    "Fringillidae"= 10,
    "Furnariida"= 3,
    "Hirundinidae"= 11,
    "Locustelloidea"= 15,
    "Malaconotoidea"= 5,
    "Meliphagoidea"= 4,
    "Motacillidae"= 22,
    "Muscicapoidea"= 18,
    "Nectariniidae"= 19,
    "Orioloidea"= 6,
    "Paridae"= 9,
    "Passeridae"= 21,
    "Petroicidae"= 8,
    "PloceidaeEstrildidae"= 20,
    "Pycnonotidae"= 13,
    "Sylvioidea"= 16,
    "Tyrannida" = 2)

## Plotting the tree and getting the tip orders
tip_colours_passeriformes_family <- plot.short.tree(tree, shapespace, "level2", tip.order = tip_order)
save(tip_colours_passeriformes_family, file = "../Data/Processed/tip_colours_passeriformes_family.rda")

## Plotting the ellipses
for(i in 1:length(tip_order)) {
    ## Plot each pannel
    wrap.plot.ellipses(i, tip_colours_passeriformes_family, family_shapespace, results$family_results_between)
}


## Plotting the aligned and scale ellipses for the superorders
par(bty = "n")
lims <- c(-1/3, 1/3) # c(-1.25, 1.25)
plot(NULL, xlim = lims, ylim = lims, xaxt = "n", yaxt = "n", xlab = "n", ylab = "n")
abline(v = 0, col = "grey", lwd = 0.5)
abline(h = 0, col = "grey", lwd = 0.5)
covar.plot(suborder_shapespace, ellipses = mean,
           col = match.col(suborder_shapespace, tip_colours_passeriformes_suborder),
           legend = FALSE, points = FALSE, scale = "phylogeny",
           lines.lwd = c(rep(1, length(tip_colours_passeriformes_suborder)), 3),
           add = TRUE, n = 100)

## PLOTTING THE ORDERS
par(bty = "n")
lims <- c(-1/3, 1/3) # c(-1.25, 1.25)
plot(NULL, xlim = lims, ylim = lims, xaxt = "n", yaxt = "n", xlab = "n", ylab = "n")
abline(v = 0, col = "grey", lwd = 0.5)
abline(h = 0, col = "grey", lwd = 0.5)
covar.plot(family_shapespace, ellipses = mean,
           col = match.col(family_shapespace, tip_colours_passeriformes_family),
           legend = FALSE, points = FALSE, scale = "phylogeny",
           lines.lwd = c(rep(0.5, length(tip_colours_passeriformes_family)), 3),
           add = TRUE, n = 100)
dev.off()

```
