---
title: "Bird beak's elaboration and innovation"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
bibliography: references.bib
output:
  html_document:
    fig_width: 8
    fig_height: 8
---

This section contains the code for reproducing the analyses. To get the details, refer to 03-elaboration_innovation_analyses.Rmd.

```{r, eval = TRUE, echo = FALSE, results = 'hide', message = FALSE, warning = FALSE, print = FALSE}
library(dispRity)
```

# All birds shapespace analyses

```{r, eval = TRUE, echo = FALSE}
## Load the data
load(file = "../Data/Processed/shapespace_allbirds_lvl_superorder_order.rda")
## Select the data
shapespace <- shapespace_allbirds_lvl_superorder_order[[1]]$space
tree <- shapespace_allbirds_lvl_superorder_order[[1]]$consensus_tree
## Clean garbage
rm(shapespace_allbirds_lvl_superorder_order)

## Load the covar
load(file = "../Data/Processed/shapespace_allbirds_lvl_superorder_order.MCMCglmm")
shapespace_allbirds_lvl_superorder_order <- shapespace_allbirds_lvl_superorder_order[[1]]

## Get the levels
phylo_lvl <- which(MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order) == "animal")
super_lvl <- grep("level1_", MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order))
order_lvl <- grep("level2_", MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order))

## Creating the subsets
superorder_shapespace <- MCMCglmm.subsets(n = 1000, # Just run it on 1k matrices for now
      data          = shapespace,
      posteriors    = shapespace_allbirds_lvl_superorder_order,
      group         = MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order)[c(super_lvl, phylo_lvl)],
      rename.groups = c(levels(shapespace$level1)[-1], "phylogeny")) #[-1] is because the first level is ""

order_shapespace <- MCMCglmm.subsets(n = 1000, # Just run it on 1k matrices for now
      data          = shapespace,
      posteriors    = shapespace_allbirds_lvl_superorder_order,
      group         = MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order)[c(order_lvl, phylo_lvl)],
      rename.groups = c(levels(shapespace$level2)[-1], "phylogeny")) #[-1] is because the first level is ""
## Clean garbage
rm(shapespace_allbirds_lvl_superorder_order)
```

First we can visualise the global bird shape space (or at least the 2 first of the 8 dimensions):

```{r, message = FALSE, warning = FALSE, fig.height = 8, fig.width = 8, echo = FALSE}
## The ggplot color panel
gg.color.hue <- function(n) {
    grDevices::hcl(h = seq(15, 375, length = n + 1), l = 65, c = 100)[1:n]
}

# colour.palette <- rainbow
colour.palette <- gg.color.hue
```

```{r, echo = FALSE}
## Quick load
load(file = "../Data/Processed/shapespace_allbirds_lvl_superorder_order_results_list.rda")
results <- shapespace_allbirds_lvl_superorder_order_results_list
rm(shapespace_allbirds_lvl_superorder_order_results_list)
```

## Phylogeny window (detailed)

```{r}
## Plotting the ellipses
plot.one.ellipse <- function(data, name.col, x = TRUE, y = TRUE, main = "", legend = FALSE, with.phylo = FALSE) {

    ## Get the PC %ages
    if(x || y) {
        vars <- dispRity::variances(data$matrix[[1]])
        pc_var <- round((vars/sum(vars)*100), 2)
    }

    ## Do the empty plot
    plot(NULL, xlim = c(-1.25, 1.25), ylim = c(-1.25, 1.25), xaxt = "n", yaxt = "n", xlab = ifelse(x, paste0("PC1 (", pc_var[1], "%)"), ""), ylab = ifelse(y, paste0("PC2 (", pc_var[2], "%)"), ""), main = main)
    if(x) axis(1)
    if(y) axis(2)
    abline(v = 0, col = "grey", lwd = 0.5)
    abline(h = 0, col = "grey", lwd = 0.5)

    if(!with.phylo) {
        subsets <- names(name.col)
        cols <- name.col
    } else {
        subsets <- c("phylogeny", names(name.col))
        cols <- c("grey", name.col)
    }
    covar.plot(get.subsets(data, subsets = subsets),
           col = cols,
           ellipses = mean,
           legend = FALSE,
           points = FALSE,
           cex = 0.5, apply.to.VCV = TRUE,
           lwd = 4,
           add = TRUE,
           legend = legend)
}
## Plot the projection/rejection
plot.one.proj.rej <- function(data, name.col, x = TRUE, y = TRUE, main = "") {

    ## Get the proj/rej
    elaboration <- get.disparity(data$position, concatenate = FALSE)
    exploration <- get.disparity(data$distance, concatenate = FALSE)

    ## Get the correct group
    if(length(ID <- which(names(test) %in% names(name.col))) < 1) {
        ID <- which(names(test) %in% paste0(names(name.col), ":phylogeny"))
    }
    elaboration <- c(elaboration[[ID]])
    exploration <- c(exploration[[ID]])

    ## Change the colours
    col <- c(name.col, adjustcolor(name.col, alpha.f = 0.5))
    
    ## Set the limits
    quant_95 <- quantile(c(elaboration, exploration), prob = 0.975)
    lim_up <- c(ceiling(quant_95/5)*5)

    ## Plot the results
    boxplot(cbind(elaboration, exploration), horizontal = TRUE, ylim = c(0,lim_up), col = col, las = 1, xaxt = "n", yaxt = "n")
    if(x) {
        axis(1, at = seq(from = 0, to = lim_up, by = 5), labels = seq(from = 0, to = lim_up, by = 5))
    }
    if(y) {
        axis(2, at = c(1, 2), labels = c("exploration", "innovation"), las = 2)
    }
}

# pdf(file = "Figure_1a.pdf", height = 11, width = 5.5)
# ## Plot the phylo ellipse
# grey_palette <- c(colour.palette(8), "grey")
# par(mfrow = c(2,1), bty = "n")
# plot.one.ellipse(superorder_shapespace, ID = c(1,9), colours = grey_palette, x = TRUE, y = TRUE, main = "A")
# legend("topright", lwd = 5, col = grey_palette[c(1,9)], lty = 1, legend = c("Aequornithes' median variance-covariance", "Overall phylogenetic's median variance-covariance"), bg = "white")
# plot.one.proj.rej(results$super_results_between, ID = 1, colours = grey_palette)
```



```{r}
box_size <- 1.5
pdf(file = "../Manuscript/Figures/Figure_1b.pdf", height = 2*5, width = box_size*12)
## Global window

layout_matrix <- layout(cbind(
                        rbind(matrix(1, ncol = 2, nrow = 3),
                              matrix(2:5, ncol = 2, nrow = 2, byrow = TRUE)),
                        matrix(6:((27*2)+1), ncol = 10, nrow = 5, byrow = TRUE)
                        ))

# layout.show(layout_matrix)

# layout_matrix <- layout(cbind(matrix(1, ncol = 1, nrow = 27),
#                               matrix(2:((27*2)+1), ncol = 2, nrow = 27, byrow = TRUE)))
# layout.show(layout_matrix)


## Plotting the tree

tree <- ladderize(tree)
## Get the tip_values
orders_lvl <- shapespace$level2
superorders_lvl <- shapespace$level1

## Select the level
selected_level <- coloured_levels <- orders_lvl

## Replace the order levels as colours
colour_palette <- c("grey", colour.palette(length(levels(coloured_levels)[-1])))
levels(coloured_levels) <- c("grey", colour.palette(length(levels(coloured_levels)[-1])))
# par(mar = c(1, 1, 1, 1)+0.1)
# plot(tree, show.tip.label = FALSE, edge.color =  match.tip.edge(as.character(coloured_levels), tree, replace.na = "grey"))

## Shorten the tree
selected_tips <- character()
for(one_level in 2:length(levels(selected_level))) {
    selected_tips[one_level-1] <- rownames(shapespace)[which(selected_level == levels(selected_level)[one_level])[1]]
    names(selected_tips)[one_level-1] <- levels(selected_level)[one_level]
}

## Shorten the tree
tree_short <- drop.tip(tree, tip = tree$tip.label[!(tree$tip.label %in% selected_tips)])
tree_short$tip.label <- names(selected_tips)[match(tree_short$tip.label, selected_tips)]

## Setting the tips edges colours
tip_edges <- match.tip.edge(tree_short$tip.label, tree_short, replace.na = "grey")
## Rainbow the tip edges
tip_edges[!(tip_edges %in% "grey")] <- rev(colour.palette(Ntip(tree_short)))
## Plotting the tree
par(mar = c(0, 0, 0, 0)+0.1)
plot(tree_short, show.tip.label = TRUE, edge.color = tip_edges, edge.width = 3, cex = 1)
# tiplabels()


## Matching the order and the colours to the ladderised tree
tip_order <- c(
    "Tinamiformes"= 1,
    "Galliformes"= 3,
    "Anseriformes"= 2,
    "Otidiformes"= 7,
    "Cuculiformes" = 8,
    "Gruiformes" = 9, 
    "Musophagiformes" = 10,
    "Procellariiformes" = 12,
    "Sphenisciformes" = 11,
    "Ciconiiformes" = 13,
    "Pelecaniformes"= 15,
    "Suliformes" = 14,
    "Podicipediformes" = 4,
    "Columbiformes" = 6,
    "Pterocliformes" = 5,
    "Charadriiformes" = 18,
    "Trogoniformes" = 21,
    "Bucerotiformes" = 22,
    "Coraciiformes" = 23,
    "Piciformes" = 24,
    "Strigiformes" = 20,
    "Accipitriformes" = 19, 
    "Falconiformes" = 25,
    "Psittaciformes" = 26,
    "Passeriformes" = 27,
    "Caprimulgiformes" = 16, 
    "Apodiformes" = 17)
tip_colours <- colour.palette(Ntip(tree_short))
names(tip_colours) <- names(sort(tip_order))
# par(bty = "n", mar = c(1, 1, 1, 1)+0.1)
# plot(rep(1,27), 1:27, col = "white")
# labs <- names(tip_colours)
# cols <- tip_colours
# text(x = rep(1,27), y = 1:27, label = rev(labs), col = rev(cols))

for(i in 1:length(tip_order)) {
    ## Select the colour and name
    name.col <- tip_colours[match(sort(names(tip_colours)), names(tip_colours))][i]

    ## Plot the ellipse
    par(bty = "n", mar = c(1, 1, 1, 1)+0.1)
    plot.one.ellipse(order_shapespace, name.col, x = FALSE, y = FALSE, with.phylo = TRUE)
    text(0,1.2, names(name.col), cex = 1.5, col = name.col)

    ## Plot the elaboration/exploration
    par(bty = "n", mar = c(2, 1, 1, 1)+0.1)
    plot.one.proj.rej(results$order_results_between, name.col, x = TRUE, y = FALSE)
}
dev.off()

```