---
title: "Bird beak's elaboration and innovation"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
bibliography: references.bib
output:
  html_document:
    fig_width: 8
    fig_height: 8
---


```{r, eval = TRUE, echo = FALSE, results = 'hide', message = FALSE, warning = FALSE, print = FALSE}
library(dispRity)
source("../Functions/ploting.utilities.R")
source("../Functions/correlations.utilities.R")
```

## Loading the data

```{r, eval = TRUE, echo = TRUE}
## Load the data
load(file = "../Data/Processed/shapespace_allbirds_lvl_superorder_order.rda")
## Select the data
shapespace <- shapespace_allbirds_lvl_superorder_order[[1]]$space
tree <- shapespace_allbirds_lvl_superorder_order[[1]]$consensus_tree
## Clean garbage
rm(shapespace_allbirds_lvl_superorder_order)

## Load the covar
load(file = "../Data/Processed/shapespace_allbirds_lvl_superorder_order.MCMCglmm")
shapespace_allbirds_lvl_superorder_order <- shapespace_allbirds_lvl_superorder_order[[1]]

## Get the levels
phylo_lvl <- which(MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order) == "animal")
super_lvl <- grep("level1_", MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order))
order_lvl <- grep("level2_", MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order))

## Creating the subsets
superorder_shapespace <- MCMCglmm.subsets(, # Just run it on 1k matrices for now
      data          = shapespace,
      posteriors    = shapespace_allbirds_lvl_superorder_order,
      group         = MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order)[c(super_lvl, phylo_lvl)],
      rename.groups = c(levels(shapespace$level1)[-1], "phylogeny")) #[-1] is because the first level is ""

order_shapespace <- MCMCglmm.subsets(, # Just run it on 1k matrices for now
      data          = shapespace,
      posteriors    = shapespace_allbirds_lvl_superorder_order,
      group         = MCMCglmm.levels(shapespace_allbirds_lvl_superorder_order)[c(order_lvl, phylo_lvl)],
      rename.groups = c(levels(shapespace$level2)[-1], "phylogeny")) #[-1] is because the first level is ""
## Clean garbage
rm(shapespace_allbirds_lvl_superorder_order)

## Loading the projection/rejections results
load(file = "../Data/Processed/shapespace_allbirds_lvl_superorder_order_results_list.rda")
results <- shapespace_allbirds_lvl_superorder_order_results_list
rm(shapespace_allbirds_lvl_superorder_order_results_list)
```

# Checking elaboration and innovation values through time (clades)

```{r, eval = TRUE, echo = TRUE}
## Get all the statistics
super_orders_elaboration <- summary(results$super_results_between$position)
super_orders_innovation <- summary(results$super_results_between$distance)
orders_elaboration <- summary(results$order_results_between$position)
orders_innovation <- summary(results$order_results_between$distance)

## Get all the tree ages
load("../Data/Processed/ploting_data.rda")
load("../Data/Processed/clade_info.rda")

get.clade.age <- function(name, info, tree) {
  return(list(age = max(dispRity::tree.age(keep.tip(tree, info[[name]]$species))$ages), col = info[[name]]$col))
}

super_age_info <- t(sapply(unlist(strsplit(super_orders_elaboration$subsets, split = ":phylogeny")), get.clade.age, info = clade_info$super_orders, tree = ploting_data$consensus_tree))
order_age_info <- t(sapply(unlist(strsplit(orders_elaboration$subsets, split = ":phylogeny")), get.clade.age, info = clade_info$orders, tree = ploting_data$consensus_tree))

## Table that for easy plotting
super_orders_elaboration <- cbind(super_orders_elaboration, super_age_info, pch = 19)
super_orders_innovation <- cbind(super_orders_innovation, super_age_info, pch = 19)
orders_elaboration <- cbind(orders_elaboration, order_age_info, pch = 21)
orders_innovation <- cbind(orders_innovation, order_age_info, pch = 21)
elaboration_plot_data <- rbind(super_orders_elaboration, orders_elaboration)
innovation_plot_data <- rbind(super_orders_innovation, orders_innovation)

## Empty plot
plot.age.data <- function(data, ylab, xlab, main = "") {
  plot(NULL, xlab = xlab, ylab = ylab, main = main,
       xlim = rev(range(pretty(range(data$age)))),
       ylim = range(pretty(range(data[c("2.5%", "25%", "75%", "97.5%")]))))
  ## Adding the lines for each clade
  for(i in 1:nrow(data)) {
    lines(x = rep(data[i, "age"][[1]], 2), y = data[i, c("2.5%", "97.5%")], lty = 2, col = data[i, "col"][[1]])
    lines(x = rep(data[i, "age"][[1]], 2), y = data[i, c("25%", "75%")], lty = 1, lwd = 2, col = data[i, "col"][[1]])
    points(x = data[i, "age"][[1]], y = data[i, "obs.median"], pch = data[i, "pch"], col = data[i, "col"][[1]])
  }
}

pdf(height = 14, width = 7, file = "../Manuscript/Figures/Elaboration_and_innovation_clade_through_time.pdf")
par(mfrow = c(2,1))
plot.age.data(elaboration_plot_data, ylab = "Elaboration", xlab = "", main = "Clade's elaboration/innovation\nthrough time")
legend("topleft", pch = 21, col = unlist(orders_elaboration$col), legend = rownames(orders_elaboration), cex = 0.7)
legend("top", pch = 19, col = unlist(super_orders_elaboration$col), legend = rownames(super_orders_elaboration), cex = 0.7)
plot.age.data(innovation_plot_data, ylab = "Innovation", xlab = "Time (Mya)")
dev.off()
```

# Checking elaboration and innovation values through time (species)

```{r, eval = TRUE, echo = TRUE}
## Get all the statistics
super_orders_elaboration <- summary(results$super_results_within$position)[-9,]  #-9 is for removing the "phylogeny" element
super_orders_innovation <- summary(results$super_results_within$distance)[-9,]
orders_elaboration <- summary(results$order_results_within$position)[-28,] #-28 is for removing the "phylogeny" element
orders_innovation <- summary(results$order_results_within$distance)[-28,]

## Get all the tree ages
load("../Data/Processed/ploting_data.rda")
load("../Data/Processed/clade_info.rda")

super_age_info <- t(sapply(unlist(strsplit(super_orders_elaboration$subsets, split = ":phylogeny"))[-9], get.clade.age, info = clade_info$super_orders, tree = ploting_data$consensus_tree)) #-9 is for removing the "phylogeny" element
order_age_info <- t(sapply(unlist(strsplit(orders_elaboration$subsets, split = ":phylogeny"))[-28], get.clade.age, info = clade_info$orders, tree = ploting_data$consensus_tree)) #-28 is for removing the "phylogeny" element

## Table that for easy plotting
super_orders_elaboration <- cbind(super_orders_elaboration, super_age_info, pch = 19)
super_orders_innovation <- cbind(super_orders_innovation, super_age_info, pch = 19)
orders_elaboration <- cbind(orders_elaboration, order_age_info, pch = 21)
orders_innovation <- cbind(orders_innovation, order_age_info, pch = 21)
elaboration_plot_data <- rbind(super_orders_elaboration, orders_elaboration)
innovation_plot_data <- rbind(super_orders_innovation, orders_innovation)

pdf(height = 14, width = 7, file = "../Manuscript/Figures/Elaboration_and_innovation_species_through_time.pdf")
par(mfrow = c(2,1))
plot.age.data(elaboration_plot_data, ylab = "Elaboration", xlab = "", main = "Species's elaboration/innovation\nthrough time (per clade)")
legend("topright", pch = 21, col = unlist(orders_elaboration$col), legend = unlist(orders_elaboration$subsets), cex = 0.7)
legend("top", pch = 19, col = unlist(super_orders_elaboration$col), legend = unlist(super_orders_elaboration$subsets), cex = 0.7)
plot.age.data(innovation_plot_data, ylab = "Innovation", xlab = "Time (Mya)")
dev.off()
```
