---
title: "Updates a Procrustes and a PCA"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 6
    fig_height: 6
---

In this script we will be looking at how to update both a Procrustes superimposition (GPA) and a PCA by projecting new specimens in it.
The goal is to use the GPA and PCA from a previous dataset (published with Guillerme et al 2023 - Science Advances) and to project new specimens onto it.

# The pseudo math:

In pseudo math, the whole procedure is something like:

 1. Procrustes = multiplying the landmark data `D` by some estimated transformation matrix `M1`.
 2. PCA = multiplying the procrustes data `M1*D` by some transformation matrix (the eigvenctors) `M2`.

So we should technically be able to get the numerical values from both transformation matrices and use them to feed in the new data to them to have something like `M2*M1*D'` where `D'` are the new landmarks.
In that case if `M2*M1*D = traitspace`, then if `D' = D`, we should get the exact same results (a traispace with _n_ species with all the same coordinates).
And if `D' = D + x` where `x` are _m_ new specimens, we should have a traitspace with the exact same results for `D` and new results of `x` that are "correctly" positioned into that space.

# Mapping the chaffinches on the whole traitspace

```r #, eval = FALSE, echo = FALSE}
## Get some random shapes for cross-validation
# Read in landmark data and landmark pairs file (necessary for enforcing symmetry later)
beaks <- readRDS("../Data/Raw/Beak_data/2020_06_19_MMB_LANDMARKS_ALL.rds")
pairs <- read.table("../Data/Raw/Beak_data/landpairs.txt")

# Remove some annoying extra labelling on individual beaks
spp <- gsub("_1|_2|_3|_4|_5|_6", "", beaks$species)

# Get unique names
uspp <- unique(spp)

# Create empty array and assign species names to each element in the array
spp_mshape_all <- array(NA, dim=c(79, 3, length(uspp)))
dimnames(spp_mshape_all)[[3]] <- uspp

# Loop over all species, read in individual user landmarks, apply procrustes alignment, forcing symmetry (other than for species with true asymmetry)
# Store mean shape configuration for each species as the species levels set of landmarks for downstream analyses

for (i in 1:length(uspp)) {
    idx <- which(spp==uspp[i])
    tmp_beaks <- beaks[[1]][,,idx]
    spp_alig <- procSym(tmp_beaks, CSinit=FALSE, scale=FALSE, pairedLM=as.matrix(pairs))
    
    if (sum(grep("Loxia_", uspp[i]),  grep("Anarhynchus_", uspp[i]))>0) {
        spp_alig <- procSym(tmp_beaks, CSinit=FALSE, scale=FALSE)
    }
    spp_mshape <- spp_alig$mshape
    spp_mshape_all[,,i] <- spp_mshape
    print(i)
}

## Selecting 20 random bird
randoms = c(sample(1:8748, 17), 753, 6077, 918) # hummingbird = 753, flamingo = 6077, shoebill = 918
testing_projection_shapes <- spp_mshape_all[,, randoms]
save(testing_projection_shapes, file = "../Data/Processed/testing_projection_shapes.rda")
```

Here are the new chaffinches projected onto the former traitspace.
The blue circles are the old chaffinches that were present in the dataset before.

```r #, echo = FALSE}
## Loading the entire bird GPA
library(Morpho)
whole_gpa <- readRDS("../Data/Raw/Beak_data/2020_08_07_MMB_MORPHO_SHAPESPACE_FULL.rds")

## Reading in the chaffinches
land_pairs <- read.table("../Data/Raw/Beak_data/landpairs.txt")

## Read all the chaffinches
path <- "../Data/Raw/Beak_data/Chaffinch_data/"
individuals <- list.files(path)
all_individuals <- list()
while(length(individuals) != 0) {
    file <- paste0(path, individuals[1], "/", list.files(paste0(path, individuals[1]))) 
    if(grepl(".nts", file)) { 
        ## Does contain a file
        data <- geomorph::readland.nts(paste0(path, individuals[1], "/", list.files(paste0(path, individuals[1]))))
        name <- paste0(strsplit(individuals[1], split = "_")[[1]][1:4], collapse = "_")
        all_individuals[[length(all_individuals) + 1]] <- data[, , 1]
        names(all_individuals)[length(all_individuals)] <- name
    } #else {
        # print(paste0(file, ": empty"))
    # }
    individuals <- individuals[-1]
}


## Get some random beak shapes for cross validating
load(file = "../Data/Processed/testing_projection_shapes.rda")

## Converting into an array
new_individuals <- simplify2array(all_individuals)
n_new <- dim(new_individuals)[[3]] 
## Add the cross validation specimens
new_individuals <- abind::abind(new_individuals, testing_projection_shapes)

## Project them! (*-1 is to flip it around)
# updated_pca <- update.gpa.pca(whole_gpa, new_individuals)*-1

# No pipeline
# Get the CPA
original_data <- whole_gpa
new_landmarks <- new_individuals

## Running the pca on the tangent space data
original_pca <- prcompfast(original_data$tan*-1)

## Project the new specimens on the original GPA
new_data <- Morpho::align2procSym(original_data, new_landmarks)

## New data needs to be projected on the tangent space because of symmetry.
new_proj_symtan <- sweep(new_data, 1:2, whole_gpa$mshape)
new_proc_tan <- vecx(new_proj_symtan)

new_pca <- stats::predict(original_pca, newdata = new_proc_tan)#array.to(new_proc_tan, to = "matrix"))
## Combine the new and old matrices for the output PCA
updated_pca <- rbind(original_pca$x*-1, new_pca)


## Good locations
plot(whole_gpa$PCscores[,c(1,2)], col = "grey", main = "New chaffinches projected onto the former space")
points(updated_pca[-c((dim(whole_gpa$PCscores)[1]+1): dim(updated_pca)[1]), c(1,2)], pch = 19, cex = 0.5, col = "grey")

## Plot the chaffinches to see where they lay:
fringillas <- which(grepl("Fringilla", rownames(whole_gpa$PCscores)))
points(updated_pca[c((dim(whole_gpa$PCscores)[1]+1):(dim(updated_pca)[1]-20)[1]), c(1,2)], pch = 19, cex = 0.5, col = "orange")
points(whole_gpa$PCscores[fringillas,c(1,2)], pch = 21, col = "blue")
legend("bottomright", pch = c(21, 19, 21, 19), col = c("grey", "grey", "blue", "orange"), pt.cex = c(1, 0.5, 1, 0.5), legend = c("original PCA", "updated PCA", "Fringilla (original)", "New chaffinches"))
```

Looks all good but then I thought of doing a sanity check: do specimens that were present in the traitspace before get reprojected in the exact same space when running through the pipeline?
I.e. if the "new" specimens are actually old ones, do they fall back in their exact location (we want the answer to be yes for the results to be exact and reusable).
Here are twenty spread specimens:

```r #, echo = FALSE}
## But problem
## Good locations
plot(whole_gpa$PCscores[,c(1,2)], col = "grey", main = "Sanity check")
points(updated_pca[-c((dim(whole_gpa$PCscores)[1]+1): dim(updated_pca)[1]), c(1,2)], pch = 19, cex = 0.5, col = "grey")

## Test testing ones
points(whole_gpa$PCscores[dimnames(testing_projection_shapes)[[3]], c(1,2)], pch = 21, col = "darkgreen")
points(updated_pca[c((dim(whole_gpa$PCscores)[1]+1+n_new):dim(updated_pca)[1]), c(1,2)], pch = 19, cex = 0.5, col = "darkgreen")
legend("bottomright", pch = c(21, 19, 21, 19), col = c("grey", "grey", "darkgreen", "darkgreen"), pt.cex = c(1, 0.5, 1, 0.5), legend = c("original PCA", "updated PCA", "Original spec", "Reprojected spec"))
```

Unfortunately they don't project where they were supposed to and there is some kind of "pull" to the center of the trait space.
This is because of the method to reproject the procrustes actually recalculates the mean shape each time.
I still need to tinker with `Morpho::align2procSym` so that it doesn't.



```r #, eval = FALSE, echo = FALSE}
orp <- function(A, mshape=NULL) { 
  p <- dim(A)[1]
  k <- dim(A)[2]
  n <- dim(A)[3]
  if (is.null(mshape))
      mshape <- arrMean3(A)
  
  m.size <- cSize(mshape)
  Xc <- as.vector(mshape/m.size)
  X <- vecx(A)/m.size
  ##direction along mshape onto plane
  XtoPlane <- t(apply(X,1,function(x){x <- t(c(crossprod(x,Xc))*Xc)}))
  X1 <- X-XtoPlane
  X1 <- t(X1)+Xc
  proj <- array(X1, dim=c(p, k, n))*m.size
  return(proj)
}


## Testing align2procSym without changing the mean
new_individuals <- testing_projection_shapes
original_data <- whole_gpa
new_landmarks <- new_individuals


## Internal logic for align2procSym
n <- dim(new_landmarks)[3]
atts <- attributes(whole_gpa)
newdatarot <- new_landmarks

# Centroid Sizing -> skipped (cSizes all equal 1 already) -> maybe cSize needs to be a bit smaller? 0.95 seems to be the correct amount to get them to the right dimension.
mysize <- apply(new_landmarks,3,cSize)
for (i in 1:n){
    new_landmarks[,,i] <- new_landmarks[,,i]/mysize[i]
}

## The mean shape from the previously calculated gpa

## This value needs to be multiplied by 1.048-ish for some reason or 0.954
prev_mean_shape <- whole_gpa$mshape # / 0.954 # * 1.048

## n Previous specimens = 8748
## n New specimens = 20

## Kind of works.
scalars <- seq(from = 0.9538, to = 0.9552, length.out = 20)

for (i in 1:n) {

    ## New shape should be updated each time?
    prev_mean_shape <- whole_gpa$mshape / scalars[i]
    ## Test solution: update gpa (and mshape) one spec at the time? Like:
    # updated_gpa <- previous_gpa
    # for (i in 1:new_spec) {
    #     updated_gpa <- update.gpa(updated_gpa, new_specimen)
    # }

    newdatarot[,,i]  <- rotonto(x = prev_mean_shape, y = new_landmarks[,,i], scale = atts$scale, reflection = atts$reflect, centerweight = atts$centerweight, weights = atts$weights)$yrot
}





orpdata <- orp(newdatarot,whole_gpa$mshape)
noorpda <- newdatarot


## New data needs to be projected on the tangent space because of symmetry.
symtan_orpda <- sweep(orpdata, 1:2, whole_gpa$mshape) 
symtan_noorp <- sweep(noorpda, 1:2, whole_gpa$mshape)
proctan_ordat <- vecx(symtan_orpda)
proctan_norop <- vecx(symtan_noorp)

## Running the pca on the tangent space data
original_pca <- prcompfast(original_data$tan*-1)

## Getting the new PCAs
new_pca_orpda <- stats::predict(original_pca, newdata = proctan_ordat)
new_pca_norop <- stats::predict(original_pca, newdata = proctan_norop)
        # -> No difference between orp or not

## Combine the new and old matrices for the output PCA
updated_pca <- original_pca$x*-1

plot(whole_gpa$PCscores[,c(1,2)], col = "grey", main = "Sanity check")
points(updated_pca[, c(1,2)], pch = 19, cex = 0.5, col = "grey")
points(whole_gpa$PCscores[dimnames(testing_projection_shapes)[[3]], c(1,2)], pch = 21, col = "darkgreen")
points(new_pca_orpda[, c(1,2)], col = "blue", pch = 19, cex = 0.5)
# points(new_pca_norop[, c(1,2)], col = "orange", pch = 19, cex = 0.5)

ratios_orp <- new_pca_orpda[, c(1,2)] / whole_gpa$PCscores[dimnames(testing_projection_shapes)[[3]], c(1,2)]
ratios_noorp <- new_pca_norop[, c(1,2)] / whole_gpa$PCscores[dimnames(testing_projection_shapes)[[3]], c(1,2)]

plot(sort(ratios_orp[, 1]), type = "l")
lines(sort(ratios_orp[, 2]), col = "red")


points(new_pca_orpda[, c(1,2)] / ratios, col = "blue", pch = 19, cex = 0.5)


points(new_pca_orpda[, c(1,2)]/0.954, col = "blue", pch = 19, cex = 0.5)
points(new_pca_norop[, c(1,2)]*1.048, col = "orange", pch = 19, cex = 0.5)

## Something with 1.048 (or /0.95) scaling somewhere? Maybe cSize?



```